apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mi-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]  # Ajusta los verbos según los comandos que necesitas
- apiGroups: ["vmoperator.vmware.com"]
  resources: ["virtualmachines", "virtualmachineclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mi-serviceaccount
  namespace: default  # Reemplaza con tu namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mi-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: mi-serviceaccount
  namespace: default # Reemplaza con tu namespace
roleRef:
  kind: ClusterRole
  name: mi-cluster-role  # Reemplaza con el nombre de tu ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-serviceaccount
  annotations:
    kubernetes.io/service-account.name: mi-serviceaccount
type: kubernetes.io/service-account-token
